language: csharp
solution: WcfService2.sln
install:
  - nuget restore WcfService2.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release WcfService2.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./UnitTestProject2/bin/Release/UnitTestProject2.dll
