language: csharp
solution: WcfService2.sln
install:
  - nuget restore WcfService2.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release WcfService2.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./XUnitTestProject1/bin/Release/netcoreapp3.1/xunit.dll
